// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcJraSlegMfOwDgoD9W3H1vJr7rAZWKN8',
    appId: '1:828225543125:web:ede7dc634bd79ac5007b5c',
    messagingSenderId: '828225543125',
    projectId: 'acsdemo-26a99',
    authDomain: 'acsdemo-26a99.firebaseapp.com',
    storageBucket: 'acsdemo-26a99.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc1bQpXd_Yngut4xJhnYTvmmysBkKXDIk',
    appId: '1:828225543125:android:1330b4d7d0605b2f007b5c',
    messagingSenderId: '828225543125',
    projectId: 'acsdemo-26a99',
    storageBucket: 'acsdemo-26a99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqHYeGyg4ygH5IF3yoLPQJdZhXVUBEhlQ',
    appId: '1:828225543125:ios:1b317767c66e9b65007b5c',
    messagingSenderId: '828225543125',
    projectId: 'acsdemo-26a99',
    storageBucket: 'acsdemo-26a99.appspot.com',
    iosClientId: '828225543125-7o2h9r3e1r2ssuv6dnnip0sjujmc04kp.apps.googleusercontent.com',
    iosBundleId: 'com.example.azurecommunicationserviceflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqHYeGyg4ygH5IF3yoLPQJdZhXVUBEhlQ',
    appId: '1:828225543125:ios:1b317767c66e9b65007b5c',
    messagingSenderId: '828225543125',
    projectId: 'acsdemo-26a99',
    storageBucket: 'acsdemo-26a99.appspot.com',
    iosClientId: '828225543125-7o2h9r3e1r2ssuv6dnnip0sjujmc04kp.apps.googleusercontent.com',
    iosBundleId: 'com.example.azurecommunicationserviceflutter',
  );
}
